### ISSUE TITLE
TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by abmBispo** [jwt/ruby-jwt#188]
I had some problems handling this library concerning insert an array into `JWT.encode`, suposing I have a JSON in array format. Testing on padrino IRB, I got  this error:

```
TypeError: no implicit conversion of String into Integer
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt-1.5.6/lib/jwt.rb:88:in []'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt-1.5.6/lib/jwt.rb:88:in encoded_payload'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt-1.5.6/lib/jwt.rb:105:in encode'
	from (irb):12
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/padrino-core-0.13.3.3/lib/padrino-core/cli/base.rb:43:in console'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in run'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in invoke_command'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in dispatch'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in start'
	from /home/alan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/padrino-core-0.13.3.3/bin/padrino:9:in <top (required)>'
	from /home/alan/Documentos/git/phschool/backend/api/bin/padrino:17:in load'
	from /home/alan/Documentos/git/phschool/backend/api/bin/padrino:17:in <main>'
```

I have tested the command `jwt = JWT.encode([{"id"=>1}],'!chave','HS256')` an it raised. What is the best way to handle this error? In the official web page of [JWT](https://jwt.io/) is possible to convert directly from JSON array to JWT, so why I can't deal with this gem just like that?

**Comment by excpt** [comment]
The `JWT.encode` method expects a hash of claims. You should simply get the first value of the array and put that in as a parameter. There is no other way around. This is simply the current state of the ruby-jwt implementation.

**Comment by mgwidmann** [comment]
This broke in version `1.5.5` and was not backwards compatible with `1.5.4`

**Comment by RedFred7** [comment]
I have a similar problem. The cause is in the implementation of `#encode_json`. In initial versions (I use 1.5.0) it used `MultiJson.encode`. Later on it started using  `JSON.generate`, which is much more inflexible regarding types, as it expects a Hash-like or JSON::State-like object.

The thing is, patch version upgrades shouldn't really break backwards compatibility. If there is no critical reason why JSON.generate is used instead of MultiJson.encode, maybe it could be put back in next version?

**Comment by bunnrf** [comment]
This is caused by line 30 in `encode.rb`:

`      raise InvalidPayload, 'exp claim must be an integer' if payload && payload['exp'] && payload['exp'].is_a?(Time)
`

If `payload` is an array, the type error is raised when it tries to index in with a string. This could be patched by checking if `payload` is a Hash.
