### ISSUE TITLE
'DecodeError'will replace 'ExpiredSignature'

### ISSUE THREAD

**Issue by ctc1991** [jwt/ruby-jwt#260]
if you catch DecodeError, you will not get ExpiredSignature.

**Comment by excpt** [comment]
Hey @ctc1991,

thanks for reporting.

Can you provide sample code to reproduce this issue, please?

**Comment by standsleeping** [comment]
Hi there @excpt and @ctc1991. I similarly encountered this, and I believe this behavior is attributable to `DecodeError` being the [parent error class](https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/error.rb#L9) of several decoding-related error classes, one of which happens to be `ExpiredSignature`.

So what this means is that if the code rescues `DecodeError` ahead of the others, the rescue block will always catch on `DecodeError` first.

Run this example:
```ruby
DecodeError = Class.new(StandardError)
ExpiredSignature   = Class.new(DecodeError)

begin
  raise ExpiredSignature.new
rescue DecodeError => exception
  puts "#{exception.class} was raised, rescued in DecodeError"
rescue ExpiredSignature => exception
  puts "#{exception.class} was raised, rescued in ExpiredSignature"
end
```

This code outputs:
```
A ExpiredSignature was raised, rescued in DecodeError
```

Now, reverse the order of those rescue blocks, and the result becomes:
```
ExpiredSignature was raised, rescued in ExpiredSignature
```

Which is what I had originally intended when I laid out my first rescue chain.

This behavior can be avoided by making sure the code rescues `DecodeError` as a last/final measure in the rescue chain. That being said, the reason I happened to have rescued it as the **first** exception in my code was because it's the error that is raised when [no token is present](https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/decode.rb#L12) - which in my use case is most common.

By the way, @excpt if you think this is worth looking into, I'd be happy to help on making a change. We could either replace `DecodeError` as the parent to [all of these](https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/error.rb#L8-L19) with a new class (or just use StandardError for all of them), or we could create new specific error classes in the 4-or-so places where DecodeError is used explicitly and not as a parent class:
- 'Nil JSON web token'
- 'Not enough or too many segments'
- 'No verification key available'
- 'Invalid segment encoding'

Let me know! Thanks.
