### ISSUE TITLE
verify_aud only verifies that at least one aud is expected

### ISSUE THREAD

**Issue by danapczynski** [jwt/ruby-jwt#345]
The `verify_aud` method finds the intersection between expected and received audience claims, then ensures that the intersection is not empty.

from https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/verify.rb#L32-L37:
```
def verify_aud
  ...
  raise(JWT::InvalidAudError, "...") if ([*aud] & [*options_aud]).empty?
end
```

One result of this is that if the token's audience claim contains a mix of **expected and unexpected values**, `verify_aud` will not raise an error:

```
secret = "test"
token_aud_claim = ["expected", "unexpected"]
expected_aud = "expected"
token = JWT.encode({ aud: token_aud_claim }, secret, "HS256")

JWT.decode(token, secret, true, aud: expected_aud, verify_aud: true)
=> [{"aud"=>["expected", "unexpected"]}, {"alg"=>"HS256"}]
```
Nothing gets raised here, as long as the `decode` specifies at least one value from the aud claim.

We only see an error if the token's aud claim doesn't include _any_ expected values:
```
JWT.decode(token, secret, true, aud: "lmnop", verify_aud: true)

# Raises: 
JWT::InvalidAudError (Invalid audience. Expected lmnop, received ["expected", "unexpected"])
```

Shouldn't `decode` with `verify_aud: true` raise unless _every_ item within the token's aud claim is expected to be there?

**Comment by danleyden** [comment]
I believe that the logic here is correct in not requiring all of the token's claims to be matched for most cases.

Per the specification (see https://tools.ietf.org/html/rfc7519#section-4.1.3) `If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected`. The key phrase here for me  is `a value` rather than `all values`.

Working through an example, a token may have an `aud` claim of `["myhost1.mydomain", "myhost2.mydomain", "myhost3.mydomain"]`, i.e. each audience is a different server's hostname, to restrict where some data may be processed. A given server wanting to check if the token is "valid" for them, should only need to specify that their hostname is in the list, otherwise they would need to know about all of their "peers".

The specification does allow some leeway for the interpretation of this claim, but only around how the principal would "identify itself" with a value in the claim, e.g. the `aud` claim in the above example may contain a regular expression such as `["myhost[0-9]+.mydomain", "uniquehost.mydomain"]`. In this case, the receiving server could choose to identify with `myhost[0-9]+.mydomain` if their hostname was `myhost5.mydomain`. However, this case is not currently supported by the gem...

**Comment by danapczynski** [comment]
Thanks for the informative response, @danleyden. 

I believe I've allowed my implementation to distort my understanding of why and when the aud claim ought to be verified. You're right, the logic here appears to be correct.
