### ISSUE TITLE
truffleruby-head build is failing

### ISSUE THREAD

**Issue by anakinj** [jwt/ruby-jwt#396]
The truffleruby build is failing for some reason. For example https://github.com/jwt/ruby-jwt/runs/1591113294

Is there something we could do? @gogainda @eregon

**Comment by eregon** [comment]
It seems to happen within SimpleCov, I'll try to investigate tomorrow.

**Comment by eregon** [comment]
It's a bug of `docile`, doing incorrect delegation in https://github.com/ms-ati/docile/blob/f065fc32daeaf04cef387b324a8e340119ac14d0/lib/docile/fallback_context_proxy.rb#L87

It's a bug in general, as some cases with `*args, **kwargs` delegation don't work in CRuby 2.7 either (https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html#ruby-3-style-delegation).
It only triggers on TruffleRuby because it is slightly closer to 2.6 semantics when it comes to `**kwargs`.

As a workaround, I think you could have all the coverage logic (requires and SimpleCov calls) in `spec_helper.rb` under `if ENV['COVERAGE']` and make sure `COVERAGE` is not set for TruffleRuby or adapt the condition.

I'll make a PR to docile.

**Comment by anakinj** [comment]
Thanks for the investigation (and fix). I think we'll wait it out until a compatible version is released.

I think we would like to move to the other direction, always have Simplecov enabled for a better local dev experience while running the tests.

**Comment by eregon** [comment]
https://github.com/ms-ati/docile/pull/52#issuecomment-749648892 so it should work for the next build.

**Comment by anakinj** [comment]
Very nice, it seems to be working. Thanks a bunch!
