### ISSUE TITLE
How should I verify JWS with x5c certs with no CRL?

### ISSUE THREAD

**Issue by epaew** [jwt/ruby-jwt#591]
## Background
I want to use below App Store Server API. The API's response contains JWS with `x5c` header.
- https://developer.apple.com/documentation/appstoreserverapi/look_up_order_id/

I tried to decode and verify JWS with this gem and Apple's root certificate (G3), but Apple does not provide the their CRLs.

- https://www.apple.com/certificateauthority/

So I cannot pass `crls` to `#decode`, and I got `JWT::VerificationError`.

```ruby
JWT.decode(jws, nil, true, { algorithm: 'ES256', x5c: { root_certificates: root_certificates } })
```
```
/home/epaew/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jwt-2.8.1/lib/jwt/x5c_key_finder.rb:27:in `from': Certificate verification failed: unable to get certificate CRL. Certificate subject: /CN=Prod ECC Mac App Store and iTunes Store Receipt Signing/OU=Apple Worldwide Developer Relations/O=Apple Inc./C=US. (JWT::VerificationError)
```

## Question / Discussion
I identified the `JWT::VerificationError` I got is caused by this line of `JWT::X5cKeyFinder`.
- https://github.com/jwt/ruby-jwt/blob/ea1e4413dddf4309e8f8e8e1fc6f415f905dd202/lib/jwt/x5c_key_finder.rb#L36

But I do not know how is the better way to change this line.

1. Simply remove it.
2. Set the flags if the `crls` arg is not nil.
    ```diff
   -  store.flags = OpenSSL::X509::V_FLAG_CRL_CHECK | OpenSSL::X509::V_FLAG_CRL_CHECK_ALL 
   +  store.flags = OpenSSL::X509::V_FLAG_CRL_CHECK | OpenSSL::X509::V_FLAG_CRL_CHECK_ALL unless crls.nil?
    ```
3. Set the flags if the certs have URL of CRL.
    ```diff
   -  store.flags = OpenSSL::X509::V_FLAG_CRL_CHECK | OpenSSL::X509::V_FLAG_CRL_CHECK_ALL 
   +  store.flags = OpenSSL::X509::V_FLAG_CRL_CHECK | OpenSSL::X509::V_FLAG_CRL_CHECK_ALL unless root_certificates.flat_map(&:crl_uris).compact.empty?
    ```
4. Add option to skip CRL check.
    ```ruby
    JWT.decode(..., { x5c: { skip_crl_check: true } })
    ```
6. Other way.

Please give me an idea.

## Environment
- Ruby 3.2.0
- ruby-jwt 2.8.1

**Comment by anakinj** [comment]
@bdewater Sorry to bother you but do you have some insight on this one?

Is it really so that this `Apple Root CA - G3 Root` certificate does not have a CRL. Not that familiar what the requirements for CA are, but maybe CRLs are optional? What about OCSP, does Apple support that to check for revoked certificates?

From the provided options I would prefer something proposed in 4.

**Comment by bdewater** [comment]
https://www.apple.com/certificateauthority/ lists various CRLs - the question is which one applies? Can you share the `x5c` header value and/or list the certificate chain from x5c to the Apple Root CA - G3 Root? The root will most certainly not have signed your x5c leaf certificate directly and the intermediate(s) probably have the `crlDistributionPoints` extension.

This seems to be working as expected and I don't think changes are needed. It's been a while since I wrote this code but if I remember correctly `V_FLAG_CRL_CHECK` and `V_FLAG_CRL_CHECK_ALL` means OpenSSL enforces CRL checks that it would normally not do, and the JWT RFC mentions it should be validated this way. So this error means somewhere in the chain there is a CRL specified and it fails on checking it since it's absent. Cross checking with [the CLI options](https://www.openssl.org/docs/man3.3/man1/openssl-verification-options.html#:~:text=Ignored.-,%2Dcrl_check,-Checks%20end%20entity) looks to confirm this.

Side bar: I think it's normal for a root CA to not have a CRL. The trust in a root comes from it being included in your browser/OS trust store since it's self-signed. If a root needs to be revoked that'll be done by these vendors (see eg [DigiNotar](https://en.wikipedia.org/wiki/DigiNotar)) and not by the root itself. Imagine if a root is compromised, would you trust the CRL it signed? 😉 

Back to the problem at hand: I searched for a bit and based on [this announcement](https://developer.apple.com/news/?id=ytb7qj0x) and the CN in the error you mentioned, it looks like the App Store receipt signing cert is signed by the Worldwide Developer Relations (WWDR) intermediate, which in turned is signed by "Apple Inc. Root" (not "Apple Root CA - G3 Root").

Checking out "Worldwide Developer Relations - G8":
```rb
wwdr = OpenSSL::X509::Certificate.new File.read 'AppleWWDRCAG8.cer'
wwdr.find_extension('authorityKeyIdentifier').value
=> "2B:D0:69:47:94:76:09:FE:F4:6B:8D:2E:40:A6:F7:47:4D:7F:08:5E"
wwdr.crl_uris
=> ["http://crl.apple.com/root.crl"]
```
That CRL is listed on Apple's site. And for fun let's look at "Apple Inc. Root":
``rb
root = OpenSSL::X509::Certificate.new File.read 'AppleIncRootCertificate.cer'
root.find_extension('subjectKeyIdentifier').value
=> "2B:D0:69:47:94:76:09:FE:F4:6B:8D:2E:40:A6:F7:47:4D:7F:08:5E"
root.crl_uris
=> nil
```

**Comment by epaew** [comment]
This is the raw header of the JWS I received.

```ruby
encoded_header, = signed_transaction.split('.')
header = JSON.parse(Base64.decode64(encoded_header))

pp header["x5c"]
```

```
[
  "MIIEMDCCA7agAwIBAgIQfTlfd0fNvFWvzC1YIANsXjAKBggqhkjOPQQDAzB1MUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzYxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTIzMDkxMjE5NTE1M1oXDTI1MTAxMTE5NTE1MlowgZIxQDA+BgNVBAMMN1Byb2QgRUNDIE1hYyBBcHAgU3RvcmUgYW5kIGlUdW5lcyBTdG9yZSBSZWNlaXB0IFNpZ25pbmcxLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEFEYe/JqTqyQv/dtXkauDHCScV129FYRV/0xiB24nCQkzQf3asHJONR5r0RA0aLvJ432hy1SZMouvyfpm26jXSjggIIMIICBDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFD8vlCNR01DJmig97bB85c+lkGKZMHAGCCsGAQUFBwEBBGQwYjAtBggrBgEFBQcwAoYhaHR0cDovL2NlcnRzLmFwcGxlLmNvbS93d2RyZzYuZGVyMDEGCCsGAQUFBzABhiVodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDAzLXd3ZHJnNjAyMIIBHgYDVR0gBIIBFTCCAREwggENBgoqhkiG92NkBQYBMIH+MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wHQYDVR0OBBYEFAMs8Pjs6VhWGQlzE2ZOE+GX4Oo/MA4GA1UdDwEB/wQEAwIHgDAQBgoqhkiG92NkBgsBBAIFADAKBggqhkjOPQQDAwNoADBlAjEA8yRNdskp506DFdPLghLLJwAv5J8hBGLaI8DExdcPX+aBKjjO8eUo9KpfpcNYUY5YAjAPXmMXEZL+Q02adrmmshNxz3NnKm+ouQwU7vBTn0LvlM7vps2YslVTamRYL4aSs5k=",
  "MIIDFjCCApygAwIBAgIUIsGhRwp0c2nvU4YSycafPTjzbNcwCgYIKoZIzj0EAwMwZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMjEwMzE3MjAzNzEwWhcNMzYwMzE5MDAwMDAwWjB1MUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzYxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEbsQKC94PrlWmZXnXgtxzdVJL8T0SGYngDRGpngn3N6PT8JMEb7FDi4bBmPhCnZ3/sq6PF/cGcKXWsL5vOteRhyJ45x3ASP7cOB+aao90fcpxSv/EZFbniAbNgZGhIhpIo4H6MIH3MBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUu7DeoVgziJqkipnevr3rr9rLJKswRgYIKwYBBQUHAQEEOjA4MDYGCCsGAQUFBzABhipodHRwOi8vb2NzcC5hcHBsZS5jb20vb2NzcDAzLWFwcGxlcm9vdGNhZzMwNwYDVR0fBDAwLjAsoCqgKIYmaHR0cDovL2NybC5hcHBsZS5jb20vYXBwbGVyb290Y2FnMy5jcmwwHQYDVR0OBBYEFD8vlCNR01DJmig97bB85c+lkGKZMA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIBBAIFADAKBggqhkjOPQQDAwNoADBlAjBAXhSq5IyKogMCPtw490BaB677CaEGJXufQB/EqZGd6CSjiCtOnuMTbXVXmxxcxfkCMQDTSPxarZXvNrkxU3TkUMI33yzvFVVRT4wxWJC994OsdcZ4+RGNsYDyR5gmdr0nDGg=",
  "MIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNDMwMTgxOTA2WhcNMzkwNDMwMTgxOTA2WjBnMRswGQYDVQQDDBJBcHBsZSBSb290IENBIC0gRzMxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzB2MBAGByqGSM49AgEGBSuBBAAiA2IABJjpLz1AcqTtkyJygRMc3RCV8cWjTnHcFBbZDuWmBSp3ZHtfTjjTuxxEtX/1H7YyYl3J6YRbTzBPEVoA/VhYDKX1DyxNB0cTddqXl5dvMVztK517IDvYuVTZXpmkOlEKMaNCMEAwHQYDVR0OBBYEFLuw3qFYM4iapIqZ3r6966/ayySrMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMDA2gAMGUCMQCD6cHEFl4aXTQY2e3v9GwOAEZLuN+yRhHFD/3meoyhpmvOwgPUnPWTxnS4at+qIxUCMG1mihDK1A3UT82NQz60imOlM27jbdoXt2QfyFMm+YhidDkLF1vLUagM6BgD56KyKA=="
]
```

I found the URL of the CRL corresponding to the intermediate cert, thanks.
But I couldn't find the CRL for leaf cert.

```ruby
header["x5c"].each do
  cert = OpenSSL::X509::Certificate.new(Base64.decode64(_1))
  pp cert
  pp cert.crl_uris
end
```

```
#<OpenSSL::X509::Certificate
subject=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=Apple Worldwide Developer Relations,CN=Prod ECC Mac App Store and iTunes Store Receipt Signing>,
issuer=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=G6,CN=Apple Worldwide Developer Relations Certification Authority>,
serial=#<OpenSSL::BN 166451396673336810269824643773700992094>,
not_before=2023-09-12 19:51:53 UTC,
not_after=2025-10-11 19:51:52 UTC>
nil
#<OpenSSL::X509::Certificate
subject=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=G6,CN=Apple Worldwide Developer Relations Certification Authority>,
issuer=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=Apple Certification Authority,CN=Apple Root CA - G3>,
serial=#<OpenSSL::BN 198423779283306946140152871826990384204123172055>,
not_before=2021-03-17 20:37:10 UTC,
not_after=2036-03-19 00:00:00 UTC>
["http://crl.apple.com/applerootcag3.crl"]
#<OpenSSL::X509::Certificate
subject=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=Apple Certification Authority,CN=Apple Root CA - G3>,
issuer=#<OpenSSL::X509::Name C=US,O=Apple Inc.,OU=Apple Certification Authority,CN=Apple Root CA - G3>,
serial=#<OpenSSL::BN 3298319966700653461>,
not_before=2014-04-30 18:19:06 UTC,
not_after=2039-04-30 18:19:06 UTC>
nil
```

I passed the CRL of intermediate cert to `.decode`, but still I got `JWT::VerificationError`.

```ruby
ROOT_CERT_URL = "https://www.apple.com/certificateauthority/AppleRootCA-G3.cer"
CRL_URL = "http://crl.apple.com/applerootcag3.crl"

root_certificates = [
  OpenSSL::X509::Certificate.new(Faraday.get(ROOT_CERT_URL).body)
]
crls = [
  OpenSSL::X509::CRL.new(Faraday.get(CRL_URL).body)
]

JWT.decode(
  jws, nil, true, { algorithm: 'ES256', x5c: { root_certificates: root_certificates, crls: crls } }
)
```

```
/home/epaew/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jwt-2.8.1/lib/jwt/x5c_key_finder.rb:27:in `from': Certificate verification failed: unable to get certificate CRL. Certificate subject: /CN=Prod ECC Mac App Store and iTunes Store Receipt Signing/OU=Apple Worldwide Developer Relations/O=Apple Inc./C=US. (JWT::VerificationError)
```

I may understand that it is because Apple doesn't include the URL of CRL on the leaf cert, but what should I do in this case...?
Write the publickey finder like [this](https://mixi-developers.mixi.co.jp/jws-verification-for-app-store-server-notifications-version-2-storekit-2-3dae64302d8) or #471 ?

**Comment by epaew** [comment]
@bdewater 
Thank you for your advice. I didn't know about OCSP so this information helped me a lot.

However, I think it may be difficult to implement support for that validation process into ruby-jwt because if it requires online validation process...

I will try creating a simple verifier myself and close this issue if it looks okay.
